use_frameworks!

platform :ios, '13.0'

target 'LithoUtils_Example' do
  pod 'LithoOperators', git: 'https://github.com/ThryvInc/LithoOperators'
  pod 'LithoUtils', :path => '../'
  pod 'fuikit', git: 'https://github.com/ThryvInc/fuikit'
  pod 'FunNet/Combine', git: 'https://github.com/schrockblock/funnet'
  target 'LithoUtils_Tests' do
    inherit! :search_paths
  end
end
