use_frameworks!

platform :ios, '13.0'

target 'LithoUtils_Example' do
  pod 'LithoOperators', git: 'https://github.com/LithoByte/LithoOperators', branch: 'feature/cjc8/file-split'
  pod 'LithoUtils', :path => '../'
  pod 'FunNet/Combine', git: 'https://github.com/schrockblock/funnet', branch: 'feature/cjc8/update-lithooperators'
  pod 'fuikit', git: 'https://github.com/LithoByte/fuikit'
  target 'LithoUtils_Tests' do
    inherit! :search_paths
  end
end
